<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <WebRoot>WWWROOT</WebRoot>
    <RootNamespace>EmployeeManagementSystem</RootNamespace>
    <AssemblyName>EmployeeManagementSystem</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="2.19.80" />
  </ItemGroup>
</Project>
